### PR TITLE
Members Only App

### PR DESCRIPTION
**Pull request by keneogu**
A simple ruby on rails app where registered or authenticated users can create posts and also post author names are hidden from guest users.
The project is built using:.
- ruby on rails
- gem: devise gem
- bootstrap

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello Team, great job you've done so far on this project.

1. You've met most of the main requirements of the project
2. Your code in the controller is well-written and organized, from the routes methods until the private methods
3. I like the design you've made in this project. Good job
4. Thanks for the extra features you've made :)
5. Readme file is described
6. Commits messages are great
7. Linters are set up correctly

However, there are still a few changes to make in order to get the thumbs up on this project 😊🙏

## **README file**

- [x] Please remove the line which says "set up your db in database.yml file" since you're using sqlite3 adapter, there is no work needed in that file and the ```rails db:create db:migrate``` will be all that it takes to set up the database.

## **Pull Request**

- [ ] Please write a more descriptive PR summary. Try to explain to the reviewer what you've accomplished so far on this PR (What exactly do you want to get a review on) on straight short points.

## **Code and Results**

- [x] Since you're using the full routes resources for the posts controller, you should correct the functionality within it. Now you have two choices: (1) To follow the project specifications and make it only ```resources :posts, only: [:new, :create, :index]``` in your routes, therefore you'll need to edit your post controller and remove the unnecessary methods (edit, update, show, and destroy) and the related views to them as well. (2) is to modify your current logic to make it only available for the user who created the post to edit and destroy it (Now anyone can edit and destroy anyone's post) Kindly fix that. I recommend following the project specifications in this project, and later you'll have many chances to work on the full routes in more advanced ways)
posts_routes_requirement

- [x] You have many related logic code on the views. (There should not be any logic code in the views). Please move them into the helpers as ruby methods, then call them back where you need them in your views.

<hr>

When you're done with the required changes, ask for another review.
Good luck and happy coding 👨‍💻💻

<hr>

Please feel free to reach me out on Slack with the name "Mahmoud Bakr" if you have any questions regarding the required changes 😊👍

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Good job so far :+1: however some of the required changes mentioned in the last review are missing/not implemented correctly. Check my comments below :point_down:

#### Routes:
 - Specify only the used routes .i.e `resources :posts, only: [:new, :create, :index]`

#### View & Logic:
 - Remove the logic in your view [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png). Check these resources: [where do I put my code](http://codefol.io/posts/Where-Do-I-Put-My-Code), [Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)

#### Readme:
 - Add the step that includes this command: `rails db:create db:migrate` in the getting started section of your readme.

#### _Reviewed by Temitayo Adeleke_

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hello team, good job so far, however you still need to implement changes asked from previous reviewer:

- Readme:
- [ ] Add also the stem `rails db:create` before `rails db:migrate` in the getting started section in readme file
- Rubocop offenses
- [ ] Fix rubocop offenses currently you have 2

**Review by SmithVyne — CHANGES_REQUESTED** [review]
### Changes Required 🤕 👍 
Hello @keneogu your project is coming out strong, you just need to make a few more improvements to get it approved.

- Remove the edit and delete buttons when a user is not the author of a post.
- Remove the user id text box when creating a new post. The user_id for a post should be the id of the current user

Make these changes and request another code review. You should get it approved this time.

You can also reach out to me on slack, **@SmithVyne** if you have any other questions.

**Review by ghost — APPROVED** [review]
# Status: Approved 🎉 

**Hello team 👋, before you merge, please remember to add `rails db:create ` after `bundle install` in the getting started section of your readme file.**

**Congratulations and good look on your next project 😃.**

**Pull request merged**
